version: '3.4'

services:
  agentservice:
    image: agentservice:dev
    container_name: AgentService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AgentService"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\Controlcy\AgentService:/app
      - C:\Users\blackneuron\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\blackneuron\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/AgentService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  controlcyserver:
    image: controlcyserver:dev
    container_name: ControlcyServer
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ControlcyServer"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\Controlcy\ControlcyServer:/app
      - D:\Controlcy:/src
      - C:\Users\blackneuron\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\blackneuron\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/ControlcyServer.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  dbwriterservice:
    image: dbwriterservice:dev
    container_name: DbWriterService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DbWriterService"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - D:\Controlcy\DbWriterService:/app
      - C:\Users\blackneuron\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\blackneuron\.nuget\packages\:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/DbWriterService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
